version: '3.9'

services:
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    restart: always
    ports:
      - 8082:8080
    environment:
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    restart: always
    ports:
      - 8083:8080
    environment:
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    restart: always
    environment:
      SERVER_PORT: 8081
      BASYX_BACKEND: InMemory
      MQTT_CLIENTID: AAS-Env-Example-8081
      MQTT_HOSTNAME: mqtt
      MQTT_PORT: 1884
      BASYX_AASREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_SUBMODELREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry:8080
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://sm-registry:8080
      BASYX_EXTERNALURL: http://localhost:8081
    ports:
      - 8081:8081

  aas-web-ui_v2:
    image: eclipsebasyx/aas-gui:v2-240327
    ports:
      - "3000:3000"
    environment:
      AAS_REGISTRY_PATH: "http://localhost:8082"
      SUBMODEL_REGISTRY_PATH: "http://localhost:8083"
      AAS_DISCOVERY_PATH: "http://localhost:8084"
      AAS_REPO_PATH: "http://localhost:8081/shells"
      SUBMODEL_REPO_PATH: "http://localhost:8081/submodels"
      CD_REPO_PATH: "http://localhost:8081/concept-descriptions"
    restart: always

  mqtt:
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1884:1884
    volumes:
      - ./mosquitto:/mosquitto/config
    healthcheck:
      test: [ "CMD-SHELL", mosquitto_sub -p 1884 -t 'topic' -C 1 -E -i probe -W 3 ]
      interval: 5s
      retries: 3
      start_period: 1s
      timeout: 10s

  aas-mqtt-gui:
    image: emqx/mqttx-web
    ports:
      - "9090:80"
