### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

### Server / API
server:
  port: 4010
  error:
    include-message: always

open-api:
  title: AAS Transformer
  description: REST API of AAS Transformer
  version: "^project.version^"
  contact:
    name: Fraunhofer IPA
    url: https://www.ipa.fraunhofer.de
    email: benjamin.goetz@ipa.fraunhofer.de

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

spring:
  application:
    name: resource_management
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    initialization-mode: always
    driver-class-name=org: 'mariadb.jdbc.Driver'
    url: jdbc:mariadb://${database.host}:${database.port}/${database.schema}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${database.username}
    password: ${database.password}

### Database
database:
  host: localhost
  port: 3307
  schema: aas_transformer
  username: aas_transformer
  password: password

### AAS
aas:
  broker:
    host: localhost
    port: 1884
  aas-registry:
    host: localhost
    port: 8082
    url: http://${aas.aas-registry.host}:${aas.aas-registry.port}
  aas-repository:
    host: localhost
    port: 8081
    url: http://${aas.aas-repository.host}:${aas.aas-repository.port}
  submodel-registry:
    host: localhost
    port: 8083
    url: http://${aas.submodel-registry.host}:${aas.submodel-registry.port}
  submodel-repository:
    host: localhost
    port: 8081
    url: http://${aas.submodel-repository.host}:${aas.submodel-repository.port}
