### GET /api/v1/registry/{aasId} GET AAS
GET http://{{aasRegistryHost}}:{{aasRegistryPort}}/{{aasRegistryContextPath}}/api/v1/registry/{{aasId}}

### PUT /api/v1/registry/{aasId} Register AAS
PUT http://{{aasRegistryHost}}:{{aasRegistryPort}}/{{aasRegistryContextPath}}/api/v1/registry/{{aasId}}
Content-Type: application/json

# FABOS DEVICE:
{
  "modelType": {
    "name": "AssetAdministrationShellDescriptor"
  },
  "idShort": "{{aasIdShort}}",
  "identification": {
    "idType": "Custom",
    "id": "{{aasId}}"
  },
  "endpoints": [
    "http://{{aasRegistryHost}}:{{aasRegistryPort}}/{{aasRegistryContextPath}}/api/v1/registry/{{aasId}}/submodels"
  ],
  "asset": {
    "modelType": {
      "name": "Asset"
    },
    "dataSpecification": [],
    "embeddedDataSpecifications": [],
    "idShort": "{{assetIdShort}}",
    "identification": {
      "idType": "Custom",
      "id": "{{assetId}}"
    },
    "kind": "Instance"
  },
  "submodels": [
  {
      "modelType": {
        "name": "SubmodelDescriptor"
      },
      "idShort": "{{submodelIdShort}}",
      "identification": {
        "idType": "Custom",
        "id": "{{submodelId}}"
      },
      "endpoints": [
        {
          "type": "http",
          "address": "http://{{aasServerHost}}:{{aasServerPort}}/{{aasServerContextPath}}/shells/{{aasId}}/aas/submodels/{{submodelIdShort}}"
        }
      ],
      "semanticId": {}
    }
  ]
}

### DELETE /api/v1/registry/{aasId} Delete AAS
DELETE http://{{aasRegistryHost}}:{{aasRegistryPort}}/{{aasRegistryContextPath}}/api/v1/registry/{{aasId}}