global:
  scrape_interval:     %%SCRAPE_INTERVAL%% # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: %%EVALUATION_INTERVAL%% # Evaluate rules every 15 seconds. The default is every 1 minute.
  query_log_file: /prometheus/query.log

rule_files:
  - "/etc/prometheus/rules/transformer.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "%%ALERTMANAGER_HOST%%:%%ALERTMANAGER_PORT%%"

scrape_configs:
  - job_name: redis_exporter
    static_configs:
      - targets: ['%%REDIS_EXPORTER_HOST%%:%%REDIS_EXPORTER_PORT%%']
  - job_name: mosquitto_exporter
    static_configs:
      - targets: ['%%MOSQUITTO_EXPORTER_HOST%%:%%MOSQUITTO_EXPORTER_PORT%%']
  - job_name: transformer_management
    static_configs:
      - targets: ['%%AAS_TRANSFORMER_MANAGEMENT_HOST%%:%%AAS_TRANSFORMER_MANAGEMENT_PORT%%']
    metrics_path: %%AAS_TRANSFORMER_MANAGEMENT_PATH%%
  - job_name: cadvisor
    scrape_interval: %%CADVISOR_SCRAPE_INTERVAL%%
    scrape_timeout: %%CADVISOR_SCRAPE_TIMEOUT%%
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor_cadvisor'
        type: 'A'
        port: %%CADVISOR_PORT%%
  - job_name: alertmanager
    static_configs:
      - targets: ['%%ALERTMANAGER_HOST%%:%%ALERTMANAGER_PORT%%']