#!/bin/sh

CONFIG_FILE=/etc/prometheus/prometheus.yml
RULE_FILE=/etc/prometheus/rules/transformer.yml

# Config file replacements:
sed -i "s;%%SCRAPE_INTERVAL%%;${SCRAPE_INTERVAL};g" "${CONFIG_FILE}"
sed -i "s;%%EVALUATION_INTERVAL%%;${EVALUATION_INTERVAL};g" "${CONFIG_FILE}"
sed -i "s;%%REDIS_EXPORTER_HOST%%;${REDIS_EXPORTER_HOST};g" "${CONFIG_FILE}"
sed -i "s;%%REDIS_EXPORTER_PORT%%;${REDIS_EXPORTER_PORT};g" "${CONFIG_FILE}"
sed -i "s;%%MOSQUITTO_EXPORTER_HOST%%;${MOSQUITTO_EXPORTER_HOST};g" "${CONFIG_FILE}"
sed -i "s;%%MOSQUITTO_EXPORTER_PORT%%;${MOSQUITTO_EXPORTER_PORT};g" "${CONFIG_FILE}"
sed -i "s;%%AAS_TRANSFORMER_MANAGEMENT_HOST%%;${AAS_TRANSFORMER_MANAGEMENT_HOST};g" "${CONFIG_FILE}"
sed -i "s;%%AAS_TRANSFORMER_MANAGEMENT_PORT%%;${AAS_TRANSFORMER_MANAGEMENT_PORT};g" "${CONFIG_FILE}"
sed -i "s;%%AAS_TRANSFORMER_MANAGEMENT_PATH%%;${AAS_TRANSFORMER_MANAGEMENT_PATH};g" "${CONFIG_FILE}"
sed -i "s;%%CADVISOR_SCRAPE_INTERVAL%%;${CADVISOR_SCRAPE_INTERVAL};g" "${CONFIG_FILE}"
sed -i "s;%%CADVISOR_SCRAPE_TIMEOUT%%;${CADVISOR_SCRAPE_TIMEOUT};g" "${CONFIG_FILE}"
sed -i "s;%%CADVISOR_HOST%%;${CADVISOR_HOST};g" "${CONFIG_FILE}"
sed -i "s;%%CADVISOR_PORT%%;${CADVISOR_PORT};g" "${CONFIG_FILE}"

# Rule file replacements:
sed -i "s;%%HIGH_JOB_COUNT_EXPR%%;${HIGH_JOB_COUNT_EXPR};g" "${RULE_FILE}"
sed -i "s;%%HIGH_JOB_COUNT_FOR%%;${HIGH_JOB_COUNT_FOR};g" "${RULE_FILE}"
sed -i "s;%%HIGH_JOB_COUNT_KEEP_FIRING_FOR%%;${HIGH_JOB_COUNT_KEEP_FIRING_FOR};g" "${RULE_FILE}"
sed -i "s;%%HIGH_JOB_COUNT_ACTION_NAME%%;${HIGH_JOB_COUNT_ACTION_NAME};g" "${RULE_FILE}"
sed -i "s;%%NO_RUNNING_TRANSFORMATIONS_EXPR%%;${NO_RUNNING_TRANSFORMATIONS_EXPR};g" "${RULE_FILE}"
sed -i "s;%%NO_RUNNING_TRANSFORMATIONS_FOR%%;${NO_RUNNING_TRANSFORMATIONS_FOR};g" "${RULE_FILE}"
sed -i "s;%%NO_RUNNING_TRANSFORMATIONS_KEEP_FIRING_FOR%%;${NO_RUNNING_TRANSFORMATIONS_KEEP_FIRING_FOR};g" "${RULE_FILE}"
sed -i "s;%%NO_RUNNING_TRANSFORMATIONS_ACTION_NAME%%;${NO_RUNNING_TRANSFORMATIONS_ACTION_NAME};g" "${RULE_FILE}"
sed -i "s;%%EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_EXPR%%;${EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_EXPR};g" "${RULE_FILE}"
sed -i "s;%%EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_FOR%%;${EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_FOR};g" "${RULE_FILE}"
sed -i "s;%%EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_KEEP_FIRING_FOR%%;${EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_KEEP_FIRING_FOR};g" "${RULE_FILE}"
sed -i "s;%%EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_ACTION_NAME%%;${EXECUTOR_COUNTER_GREATER_INPROCESS_JOBS_ACTION_NAME};g" "${RULE_FILE}"

echo "${CONFIG_FILE}:"
cat "${CONFIG_FILE}"
echo "\n\n"

echo "${RULE_FILE}:"
cat "${RULE_FILE}"
echo "\n\n"

exec /bin/prometheus "$@"