route:
  receiver: "transformer.management"
  group_by: ["alertname"]
  continue: false
  group_wait: %%GROUP_WAIT%%
  group_interval: %%GROUP_INTERVAL%%
  repeat_interval: %%REPEAT_INTERVAL%%

receivers:
  - name: "transformer.management"
    webhook_configs:
      - send_resolved: false
        http_config:
          follow_redirects: true
          enable_http2: true
        url: http://%%AAS_TRANSFORMER_MANAGEMENT_HOST%%:%%AAS_TRANSFORMER_MANAGEMENT_PORT%%%%AAS_TRANSFORMER_MANAGEMENT_PATH%%
