route:
  receiver: "transformer.management"
  group_by: ["alertname"]
  continue: false
  # How long to initially wait to send a notification for a group
  # of alerts. Allows to wait for an inhibiting alert to arrive or collect
  # more initial alerts for the same group. (Usually ~0s to few minutes.)
  # If omitted, child routes inherit the group_wait of the parent route.
  group_wait: %%GROUP_WAIT%%
  # How long to wait before sending a notification about new alerts that
  # are added to a group of alerts for which an initial notification has
  # already been sent. (Usually ~5m or more.) If omitted, child routes
  # inherit the group_interval of the parent route.
  group_interval: %%GROUP_INTERVAL%%
  # How long to wait before sending a notification again if it has already
  # been sent successfully for an alert. (Usually ~3h or more). If omitted,
  # child routes inherit the repeat_interval of the parent route.
  # Note that this parameter is implicitly bound by Alertmanager's
  # `--data.retention` configuration flag. Notifications will be resent after either
  # repeat_interval or the data retention period have passed, whichever
  # occurs first. `repeat_interval` should be a multiple of `group_interval`.
  repeat_interval: %%REPEAT_INTERVAL%%

receivers:
  - name: "transformer.management"
    webhook_configs:
      - send_resolved: false
        http_config:
          follow_redirects: true
          enable_http2: true
        url: http://%%AAS_TRANSFORMER_MANAGEMENT_HOST%%:%%AAS_TRANSFORMER_MANAGEMENT_PORT%%%%AAS_TRANSFORMER_MANAGEMENT_PATH%%
