#!/bin/sh

CONFIG_FILE=/alertmanager/config.yml

sed -i "s;%%GROUP_WAIT%%;${GROUP_WAIT};g" "${CONFIG_FILE}"
sed -i "s;%%GROUP_INTERVAL%%;${GROUP_INTERVAL};g" "${CONFIG_FILE}"
sed -i "s;%%REPEAT_INTERVAL%%;${REPEAT_INTERVAL};g" "${CONFIG_FILE}"
sed -i "s;%%AAS_TRANSFORMER_MANAGEMENT_HOST%%;${AAS_TRANSFORMER_MANAGEMENT_HOST};g" "${CONFIG_FILE}"
sed -i "s;%%AAS_TRANSFORMER_MANAGEMENT_PORT%%;${AAS_TRANSFORMER_MANAGEMENT_PORT};g" "${CONFIG_FILE}"
sed -i "s;%%AAS_TRANSFORMER_MANAGEMENT_PATH%%;${AAS_TRANSFORMER_MANAGEMENT_PATH};g" "${CONFIG_FILE}"

cat "${CONFIG_FILE}"

exec /bin/alertmanager "$@"