### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

### Server / API
server:
  port: 4030
  error:
    include-message: always

open-api:
  title: "^project.artifactId^"
  description: REST API of AAS Transformer Executor
  version: "^project.version^"
  contact:
    name: Fraunhofer IPA
    url: https://www.ipa.fraunhofer.de
    email: benjamin.goetz@ipa.fraunhofer.de

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

spring:
  application:
    name: aas_transformer_executor
  jpa:
    hibernate:
      ddl-auto: update
  r2dbc:
    url: r2dbc:mariadb://${database.host}:${database.port}/${database.schema}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${database.username}
    password: ${database.password}
  codec:
    max-in-memory-size: 16MB
  lifecycle:
    timeout-per-shutdown-phase: 1s

### Database
database:
  host: localhost
  port: 3307
  schema: aas_transformer
  username: aas_transformer
  password: password

### TRANSFORMER
aas_transformer:
  services:
    management:
      schema: http
      host: localhost
      port: 4010
      base-url: ${aas_transformer.services.management.schema}://${aas_transformer.services.management.host}:${aas_transformer.services.management.port}
    executor:
      external_base_url: http://localhost:4030

### AAS
aas:
  aas-registry:
    host: localhost
    port: 8082
    path:
    url: http://${aas.aas-registry.host}:${aas.aas-registry.port}${aas.aas-registry.path}
  aas-repository:
    host: localhost
    port: 8081
    path:
    url: http://${aas.aas-repository.host}:${aas.aas-repository.port}${aas.aas-repository.path}
  submodel-registry:
    host: localhost
    port: 8083
    path:
    url: http://${aas.submodel-registry.host}:${aas.submodel-registry.port}${aas.submodel-registry.path}
  submodel-repository:
    host: localhost
    port: 8081
    path:
    url: http://${aas.submodel-repository.host}:${aas.submodel-repository.port}${aas.aas-repository.path}
