services:
  aas-discovery:
    image: eclipsebasyx/aas-discovery:${BASYX_VERSION}
    restart: always
    ports:
      - 8084:${AAS_AAS_DISCOVERY_PORT}
    networks:
      default:
        aliases:
          - ${AAS_AAS_DISCOVERY_HOST}
    environment:
      SERVER_PORT: ${AAS_AAS_DISCOVERY_PORT}
      SPRING_APPLICATION_NAME: AAS Discovery Service
      BASYX_AASDISCOVERYSERVICE_NAME: aas-discovery-service
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: ${AAS_BACKEND_DB_HOSTNAME}
      SPRING_DATA_MONGODB_DATABASE: aas-discovery
      SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: ${AAS_BACKEND_DB_ROOT_USERNAME}
      SPRING_DATA_MONGODB_PASSWORD: ${AAS_BACKEND_DB_ROOT_PASSWORD}
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:${BASYX_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - 8082:${AAS_AAS_REGISTRY_PORT}
    networks:
      default:
        aliases:
          - ${AAS_AAS_REGISTRY_HOST}
    environment:
      SERVER_PORT: ${AAS_AAS_REGISTRY_PORT}
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      SPRING_DATA_MONGODB_URI: mongodb://${AAS_BACKEND_DB_ROOT_USERNAME}:${AAS_BACKEND_DB_ROOT_PASSWORD}@aas-database:${AAS_BACKEND_DB_PORT}

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:${BASYX_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - 8083:${AAS_SUBMODEL_REGISTRY_PORT}
    networks:
      default:
        aliases:
          - ${AAS_SUBMODEL_REGISTRY_HOST}
    environment:
      SERVER_PORT: ${AAS_SUBMODEL_REGISTRY_PORT}
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      SPRING_DATA_MONGODB_URI: mongodb://${AAS_BACKEND_DB_ROOT_USERNAME}:${AAS_BACKEND_DB_ROOT_PASSWORD}@aas-database:${AAS_BACKEND_DB_PORT}

  aas-env:
    image: eclipsebasyx/aas-environment:${BASYX_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - ${AAS_AAS_ENV_EXT_PORT}:${AAS_AAS_ENV_PORT}
    environment:
      SERVER_PORT: ${AAS_AAS_ENV_PORT}
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: ${AAS_BACKEND_DB_HOSTNAME}
      SPRING_DATA_MONGODB_DATABASE: aas-env
      SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: ${AAS_BACKEND_DB_ROOT_USERNAME}
      SPRING_DATA_MONGODB_PASSWORD: ${AAS_BACKEND_DB_ROOT_PASSWORD}
      MQTT_CLIENTID: aas-transformer_aas-env
      MQTT_HOSTNAME: ${AAS_BROKER_HOST}
      MQTT_PORT: ${AAS_BROKER_PORT}
      BASYX_AASREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_SUBMODELREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://${AAS_AAS_REGISTRY_HOST}:${AAS_AAS_REGISTRY_PORT}
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://${AAS_SUBMODEL_REGISTRY_HOST}:${AAS_SUBMODEL_REGISTRY_PORT}
      BASYX_EXTERNALURL: http://${AAS_TRANSFORMER_HOST}:${AAS_AAS_ENV_EXT_PORT}
    networks:
      default:
        aliases:
          - ${AAS_AAS_ENV_HOST}
    depends_on:
      aas-database:
        condition: service_healthy
      aas-broker:
        condition: service_healthy
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy

  aas-gui:
    image: eclipsebasyx/aas-gui:${AAS_GUI_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "3000:${AAS_GUI_PORT}"
    environment:
      AAS_REGISTRY_PATH: "http://${AAS_TRANSFORMER_HOST}:${AAS_AAS_REGISTRY_EXT_PORT}"
      SUBMODEL_REGISTRY_PATH: "http://${AAS_TRANSFORMER_HOST}:${AAS_SUBMODEL_REGISTRY_EXT_PORT}"
      AAS_DISCOVERY_PATH: "http://${AAS_TRANSFORMER_HOST}:${AAS_AAS_DISCOVERY_EXT_PORT}"
      AAS_REPO_PATH: "http://${AAS_TRANSFORMER_HOST}:${AAS_AAS_ENV_EXT_PORT}/shells"
      SUBMODEL_REPO_PATH: "http://${AAS_TRANSFORMER_HOST}:${AAS_AAS_ENV_EXT_PORT}/submodels"
      CD_REPO_PATH: "http://${AAS_TRANSFORMER_HOST}:${AAS_AAS_DISCOVERY_EXT_PORT}/concept-descriptions"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AAS_GUI_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 5

  aas-broker:
    image: ghcr.io/fabos-ai/aas-transformer/aas-broker:2.0.15
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - ${AAS_BROKER_EXT_PORT}:${AAS_BROKER_PORT}
      - 9001:9001
    networks:
      default:
        aliases:
          - aas-broker
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    healthcheck:
      test: [ "CMD-SHELL", mosquitto_sub -p 1883 -t 'topic' -C 1 -E -i probe -W 3 ]
      interval: 5s
      retries: 3
      start_period: 1s
      timeout: 10s

  aas-database:
    image: mongo:5.0.10
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${AAS_BACKEND_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${AAS_BACKEND_DB_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - ${AAS_BACKEND_DB_HOSTNAME}
    volumes:
      - "aas_database:/data/db"
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5

volumes:
  aas_database:
