version: '3'

services:
  aas-registry:
    image: eclipsebasyx/aas-registry:1.4.0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "4000:4000"
    networks:
      default:
        aliases:
          - aas-registry
    environment:
      basyxregistry_registry_events: MQTTV2_SIMPLE_ENCODING
      basyxmqtt_server: tcp://aas-broker:1883
      basyxregistry_registry_backend: MongoDB
      basyxmongodb_dbconnectionstring: mongodb://aas-database:27017/
      basyxcontext_accesscontrolalloworigin: "*"

  aas-server:
    image: eclipsebasyx/aas-server:1.4.0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "4001:4001"
    networks:
      default:
        aliases:
          - aas-server
    environment:
      basyxmqtt_server: tcp://aas-broker:1883
      basyxaas_aas_events: MQTTV2_SIMPLE_ENCODING
      basyxaas_registry_path: http://aas-registry:4000/registry/api/v1/registry
      basyxaas_registry_host: http://${AAS_TRANSFORMER_HOST}:4001/aasServer
      basyxcontext_accesscontrolalloworigin: "*"
      basyxaas_aas_backend: MongoDB
      basyxmongodb_dbconnectionstring: mongodb://aas-database:27017/
      basyxaas_aas_aasxupload: Enabled
      waiting_for: '[{"host":"aas-registry","port":"4000"}]'

  aas-database:
    image: mongo:latest
    restart: always
    networks:
      default:
        aliases:
          - aas-database
    volumes:
      - "aas_database:/data/db"

  aas-gui:
    image: eclipsebasyx/aas-gui:v230703
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "3000:3000"
    environment:
      VITE_REGISTRY_PATH: "http://${AAS_TRANSFORMER_HOST}:4000/registry"
      VITE_AAS_SERVER_PATH: "http://${AAS_TRANSFORMER_HOST}:4001/aasServer"

  aas-broker:
    image: ghcr.io/fabos-ai/aas-transformer/aas-broker:${VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      default:
        aliases:
          - aas-broker

volumes:
  aas_database:
