version: '3'

services:
  aas-transformer:
    image: ghcr.io/fabos-ai/aas-transformer/service:${VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "4010:4010"
    networks:
      default:
        aliases:
          - aas-transformer
    environment:
      AAS_BROKER_HOST: aas-broker
      DATABASE_HOST: aas-transformer-database
      DATABASE_PASSWORD: password
    extra_hosts:
      - "${AAS_TRANSFORMER_HOST}:172.17.0.1"

  aas-transformer-init:
    image: ghcr.io/fabos-ai/aas-transformer/initializer:1.0.0-SNAPSHOT
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}

  aas-transformer-database:
    image: mariadb:10.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    networks:
      default:
        aliases:
          - aas-transformer-database
    ports:
      - "3307:3306"
    environment:
      MARIADB_USER: aas_transformer
      MARIADB_PASSWORD: ${AAS_TRANSFORMER_DATABASE_PASSWORD}
      MARIADB_DATABASE: aas_transformer
      MARIADB_ROOT_PASSWORD: ${AAS_TRANSFORMER_DATABASE_ROOT_PASSWORD}
    volumes:
      - "aas_transformer_database:/var/lib/mysql"

  aas-transformer-redis:
    image: redis:7
    command: redis-server /redis.conf
    volumes:
      - "./redis.conf/:/redis.conf"
    ports:
      - "6379:6379"

volumes:
  aas_transformer_database:
