version: '3'

services:
  aas-registry:
    image: eclipsebasyx/aas-registry:1.4.0
    ports:
      - "4000:4000"
    environment:
      basyxregistry_registry_events: MQTTV2_SIMPLE_ENCODING
      basyxmqtt_server: tcp://aas-broker:1883
      basyxcontext_accesscontrolalloworigin: "*"

  aas-server:
    image: eclipsebasyx/aas-server:1.4.0
    ports:
      - "4001:4001"
    environment:
      basyxaas_aas_events: MQTTV2_SIMPLE_ENCODING
      basyxaas_registry_path: http://aas-registry:4000/registry/api/v1/registry
      basyxmqtt_server: tcp://aas-broker:1883
      basyxcontext_accesscontrolalloworigin: "*"
      waiting_for: '[{"host":"aas-registry","port":"4000"}]'

  aas-gui:
    image: eclipsebasyx/aas-gui:v230703
    ports:
      - "3000:3000"
    environment:
      VITE_REGISTRY_PATH: "http://localhost:4000/registry"
      VITE_AAS_SERVER_PATH: "http://localhost:4001/aasServer"

  aas-broker:
    image: ghcr.io/fabos-ai/aas-transformer/aas-broker:${VERSION}
    ports:
      - "1883:1883"
      - "9001:9001"

  aas-mqtt-gui:
    image: emqx/mqttx-web
    ports:
      - "9090:80"

  aas-transformer:
    image: ghcr.io/fabos-ai/aas-transformer/service:${VERSION}
    ports:
      - "4010:4010"

  aas-transformer-database:
    image: mariadb:10.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      MYSQL_USER: aas-transformer
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: transformer
      MARIADB_ROOT_PASSWORD: password
