global:
  scrape_interval:     200ms # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 200ms # Evaluate rules every 15 seconds. The default is every 1 minute.
  query_log_file: /prometheus/query.log

scrape_configs:
  - job_name: redis_exporter
    static_configs:
      - targets: ['host.docker.internal:9121']
  - job_name: mosquitto_exporter
    static_configs:
      - targets: ['host.docker.internal:9234']
  - job_name: transformer_management
    static_configs:
      - targets: ['host.docker.internal:4010']
    metrics_path: /actuator/prometheus
  - job_name: cadvisor
    scrape_interval: 3s
    scrape_timeout: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']