{
 "title": "Transformer Container",
 "description": "This Grafana dashboard offers a basic overview of key performance metrics for Docker containers in your system.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "transformerservice", "label": "Transformer Service", "query": "management,listener,executor" },
   { "name": "queryinterval", "query": "1s" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O reads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_memory_usage_bytes{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Cached per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_memory_cache{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Writes per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Network Traffic per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent Network Traffic per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[10s])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Restarts filtered by Container Group",
     "type": "heatmap",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "count by(name) (count_over_time(container_last_seen{container_label_de_fhg_ipa_aas_transformer_container_group!=\"\", image=~\".*${transformerservice}.*\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}