{
 "title": "AAS Transformer Metrics",
 "templating": {
  "list": [
   { "name": "queryinterval", "query": "1s" }
  ]
 },
 "panels": [
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Listener Metrics",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "aas_submodel_change_count_total",
     "legendFormat": "Incoming Submodel Changes"
    },
    {
     "expr": "aas_processed_submodel_change_count_total",
     "legendFormat": "Proccessed Incoming Submodel Changes"
    },
    {
     "expr": "sum(aas_submodel_change_count_total) - sum(aas_processed_submodel_change_count_total)",
     "legendFormat": "Open submodel changes"
    }
   ]
  },
  {
   "title": "Executor Metrics",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "redis_key_size", "legendFormat": "Open Transformation Jobs" },
    { "expr": "redis_keys_count", "legendFormat": "In-process Transformation Jobs" }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Transformation Metrics over Time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "redis_keys_count", "legendFormat": "In-Process Transformation Jobs" },
    { "expr": "redis_key_size", "legendFormat": "Open Transformation Jobs" },
    {
     "expr": "aas_submodel_change_count_total",
     "legendFormat": "Submodel Changes"
    },
    {
     "expr": "aas_processed_submodel_change_count_total",
     "legendFormat": "Processes Submodel Changes"
    },
    {
     "expr": "sum(aas_submodel_change_count_total)-sum(aas_processed_submodel_change_count_total)",
     "legendFormat": "Open Submodel Changes"
    }
   ]
  },
  {
   "title": "Listener Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open submodel changes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aas_submodel_change_count_total) - sum(aas_processed_submodel_change_count_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Submodel Changes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 4, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aas_submodel_change_count_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Proccessed Incoming Submodel Changes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aas_processed_submodel_change_count_total",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Transformation Jobs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "redis_key_size", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "In-process Transformation Jobs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "redis_keys_count", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}