name: Build Prom

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build Prom docker image
        working-directory: ./docker-compose/prometheus
        run: docker compose build --no-cache prometheus
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Push docker image
        working-directory: ./docker-compose/prometheus
        run: docker compose push prometheus